version: 1
home: /Users/chathula/Desktop # Default path will be $HOME/Desktop
git:
  path: code # actual path = home/base path + this path
  repositories:
    - url: https://github.com/Chathula/chathula.dev
      name: personal-blog
    - url: https://github.com/Chathula/swr-vue
      delete: true
